id: multicloud-12DeploywithRollback
metadata:
  description: A simple deploy with added rollback functionality
  name: 12-Deploy-with-Rollback
  owner: anonymous
  scopes:
  - global
protect: false
schema: "1"
variables:
- name: imageid
  description: ID and tag of the image to be deployed.
  defaultValue: docker.io/opsmx11/restapp:simple-1.0
- name: porttoopen
  description: The port through which container can be accessed. 
  defaultValue: 8080
stages:
- config:
    continuePipeline: false
    failPipeline: true
    job: bitbucket-restapp
    master: opsmx-jenkins-master
    parameters: {}
  id: jenkins1
  inheritanceControl: {}
  inject: {}
  name: Jenkins
  type: jenkins
- config:
    account: opsmx-v2-opsmx-account
    cloudProvider: kubernetes
    manifestArtifactAccount: opsmx-restapp-account
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: simplelb
        namespace: production
      spec:
        ports:
        - name: canary
          port: "{{ porttoopen }}"
          protocol: TCP
          targetPort: "{{ porttoopen }}"
        - name: reports
          port: 9090
          protocol: TCP
          targetPort: 9090
        selector:
          app: simple
        type: NodePort
    moniker:
      app: multicloud
    relationships:
      loadBalancers: []
      securityGroups: []
    source: text
  dependsOn:
  - jenkins1
  id: deployManifest2
  inheritanceControl: {}
  inject: {}
  name: Deploy Simple LB
  type: deployManifest
- config:
    account: opsmx-v2-opsmx-account
    cloudProvider: kubernetes
    manifestArtifactAccount: opsmx-restapp-account
    manifests:
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: simple
        namespace: production
      spec:
        replicas: 1
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: simple
        strategy:
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: simple
          spec:
            containers:
            - image: "{{ imageid }}"
              imagePullPolicy: Always
              name: restapp
              ports:
              - containerPort: "{{ porttoopen }}"
                name: http
                protocol: TCP
              - containerPort: 9090
                name: prometheus
                protocol: TCP
    moniker:
      app: multicloud
    relationships:
      loadBalancers: []
      securityGroups: []
    source: text
  dependsOn:
  - deployManifest2
  id: deployManifest3
  inheritanceControl: {}
  inject: {}
  name: Deploy Simple RS/Deploy
  type: deployManifest
- config:
    failPipeline: true
    judgmentInputs:
    - value: Accept
    - value: Rollback
    notifications: []
  dependsOn:
  - deployManifest3
  id: manualJudgment4
  inheritanceControl: {}
  inject: {}
  name: Manual Judgment
  type: manualJudgment
- config:
    account: opsmx-v2-opsmx-account
    cloudProvider: kubernetes
    location: production
    manifestName: deployment simple
    numRevisionsBack: 1
  dependsOn:
  - manualJudgment4
  id: undoRolloutManifest5
  inheritanceControl: {}
  inject: {}
  name: Undo Rollout (Manifest)
  type: undoRolloutManifest
